name: 'Terraform Create'

on:
  workflow_dispatch:
    inputs:
      global_variable_name:
        description: 'Pass your global variable name'
        type: string
        required: true
      global_variable_value:
        description: 'Pass your global variable value'
        type: string
        required: true
      datadog_synthetics_test_name:
        description: 'Datadog Synthetic test Name'
        type: string
        required: false
        default: "inductiveuniversity.com"
env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  DD_APP_KEY: ${{ secrets.DD_APP_KEY }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

        #Terraform Workspace
      - name: Terraform Workspace
        run: terraform workspace new ${{ inputs.global_variable_name }} || terraform workspace select ${{ inputs.global_variable_name }}

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -var datadog_synthetics_test_name=${{ inputs.datadog_synthetics_test_name }} -var global_variable_name=${{ inputs.global_variable_name }} -var global_variable_value=${{ inputs.global_variable_value }} -out tfplan

        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        run: terraform apply "tfplan"